fix: Ignore bin dependencies in lib
lenra-io/dofigen pull request #14
Opened 2022-08-17 13:57 UTC by taorepoara

## Checklist
- [ ] I didn't over-scope my PR
- [ ] My PR title matches the [commit convention](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] I did not include breaking changes
- [ ] I included unit tests that cover my changes
- [ ] I added/updated the documentation about my changes
- [ ] I made my own code-review before requesting one

## Description of the changes
Do not load the bin dependencies in the lib crate.

## Technical highlight/advice

The `cargo install` must specify the bin feature: `cargo install dofigen -F bin`

2022-08-18 06:54 UTC, taorepoara commented
@jrouaix What do you think ?

2022-08-18 07:05 UTC, jrouaix commented
I wonder why `-F` is need when `cargo install` command.
The install command should only consider the one `bin` part of the crate so is should activate the feature itself ?
(perhaps i'm mistaken here and the required_feature does not activate the feature automaticaly ...)

2022-08-18 07:24 UTC, taorepoara commented
> I wonder why `-F` is need when `cargo install` command.
> The install command should only consider the one `bin` part of the crate so is should activate the feature itself ?
> (perhaps i'm mistaken here and the required_feature does not activate the feature automaticaly ...)

I have tried without it but the install fails because the feature is not activated.
I also tried with the `bin` option (`cargo install --path . --bin dofigen`) but the installation also fails and says explicitly that the `--features bin` option is needed because of the `required_feature`.

2022-08-22 14:09 UTC, shiipou requested changes

2022-08-22 14:09 UTC, shiipou commented on Cargo.toml
> +required-features = ["bin"]
The feature `bin` didn't give enough meaning to final user,
I think naming it `cli` can help people to know the feature it to add the command line features.

```suggestion
required-features = ["cli"]
```

2022-08-25 06:19 UTC, shiipou requested changes
I think you missed this `bin` features

2022-08-25 06:19 UTC, shiipou commented on .github/workflows/build_ci.yml
> +        args: --release -F bin --target ${{ matrix.target }}
```suggestion
        args: --release -F cli --target ${{ matrix.target }}
```

2022-08-25 06:19 UTC, shiipou commented on dofigen.yml
> +  - cargo build --release -F bin --target=x86_64-unknown-linux-musl
```suggestion
  - cargo build --release -F cli --target=x86_64-unknown-linux-musl
```

2022-08-29 06:56 UTC, shiipou approved these changes
LGTM

2022-08-29 07:09 UTC, merged